### ISSUE TITLE
Result display ?

### ISSUE THREAD

**Issue by madaratech** [SpiderLabs/Airachnid-Burp-Extension#1]
Thanks for making burp ext for this, anyway when i select target from sitemap and select the **Web Cache Deception** for scan, i don't see anything if its scanning or not, if it's found where result should display, most probably under "**issues**", just the things think is users have no idea what after he selected for scan, is it scanning or not or scanning completed or not ? may be something missing in UI for users ?

**Comment by duidelik** [comment]
The feedback is in the extension Output window. The new version will only report if the issue was not found, and add an issue to the URL if it has been found.
